### ISSUE TITLE
Feedback based on my first usage

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/generator-core-patternlib#1]
Just finished running this generator for the first time, and I had some (hopefully small) bits of feedback for the process. I thought I'd provide that in issue form. Thanks for listening! :grin: 

:warning: **Disclaimer:**
This is actually my first experience using Yeoman. My understanding is that it's a scaffolding tool designed to initialize projects quickly based on "generators" that are basically recipes for "create these files, download this stuff, build these things," but that could be completely off-base.

## Order of README is potentially counter-intuitive

Based on the current README, here's what I ended up doing...

1. Stared and blinked slowly at "step 1" before realizing that it's _actually_ step 2 (after "clone this repository locally," which for some reason my brain didn't absorb from the first sentence).
2. `npm install -g yo`
3. Stared and blinked slowly at warnings that my `node` version was out of date.
4. Asked @erikjung for help.
5. Read the rest of the README and realized the `.node-version` stuff was probably a requirement for the generator as well.
6. Followed the `.node-version` steps, then `npm install -g yo` again (and subsequent steps).
7. Moved on to the "Usage" steps, got errors.
8. Remembered that the `.node-version` step needs to happen in my project directory as well.
9. Finally ran the generator.

To summarize, my feedback is that "step 1" for "install" should be cloning the repo, and the `.node-version` stuff should be called out earlier and in reference to _both_ the "Install" and "Usage" sections.

## `toolkit.title`

For some reason, I expected when I entered the project name during the Yeoman steps that it would somehow show up in the Pattern Library masthead. This is actually a bad idea (since `npm` modules have more slug-like formats), but it made me wonder if we could prompt to populate `toolkit.title` as well? If that's a slippery slope, ignore me.

## npm scripts?

I was surprised to see us moving away from `npm start`, etc. Although I was initially skeptical about abstracting the `gulp` task, I've since moved to using something like this in my personal projects:

```
"scripts": {
    "prestart": "npm install",
    "start": "gulp --dev",
    "build": "npm install && gulp"
  }
```

The benefits being:
- No need to remind folks to run `npm install` before running build tasks.
- Nothing to re-learn if we change up the primary build tool (or the syntax it uses).

## CSS preprocessor?

It seems that in its current state, the generator assumes PostCSS (via cssnext). I :heart: PostCSS, but it's far from the market leader, and for many large organizations I think there's still benefits to using something like Sass. Is this something that can be customized as-is, should it be part of the build process, or..?

**Comment by erikjung** [comment]
@tylersticka Thanks for the feedback.

> This is actually my first experience using Yeoman. My understanding is that it's a scaffolding tool designed to initialize projects quickly based on "generators" that are basically recipes for "create these files, download this stuff, build these things," but that could be completely off-base.

You are correct. I also lack generator experience :)

> Stared and blinked slowly at "step 1" before realizing that it's actually step 2 (after "clone this repository locally," which for some reason my brain didn't absorb from the first sentence).

I actually had the same thought when I saw the README for our other [generator](https://github.com/cloudfour/generator-core-webapp). I can see how this is confusing. Normally, if you're using a "published" generator, the steps of cloning the repo and linking it would be unnecessary.

> For some reason, I expected when I entered the project name during the Yeoman steps that it would somehow show up in the Pattern Library masthead. This is actually a bad idea (since npm modules have more slug-like formats), but it made me wonder if we could prompt to populate toolkit.title as well? If that's a slippery slope, ignore me.

This can be done easily. 

> npm scripts?

Can do, will do.

> CSS preprocessor?

@lyzadanger and I chatted briefly about this, and decided to start with an opinionated generator based on our existing internal projects. We can definitely add the option to choose a CSS processor, but I think we'll need to sort out the relationship between this generator and the core generator first.

**Comment by tylersticka** [comment]
Cool, thanks for responding/explaining!

**Comment by erikjung** [comment]
@tylersticka If you want to give it another whirl, I think the actionable feedback has been addressed.

**Comment by tylersticka** [comment]
Awesome!

Only thing I noticed (and this may not be related to this generator specifically) is that the dummy-title I entered had an apostrophe which now looks like this:

![screen shot 2015-10-28 at 11 52 41 am](https://cloud.githubusercontent.com/assets/69633/10799557/ae7e1850-7d6a-11e5-81ee-20c87ebd8106.png)

**Comment by erikjung** [comment]
@tylersticka You just HAD to use an apostrophe. I'll see where it makes sense to handle the escaping.

**Comment by erikjung** [comment]
@tylersticka Turned out to be an EJS thing. It should handle your fancy characters now.

**Comment by tylersticka** [comment]
Yay!
