### ISSUE TITLE
Please remove .node-version from `app/templates`

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/generator-core-patternlib#11]
The `node-version` that gets set up by this generator is too restrictive. It's on `0.12` and we're now on `4.0.0` (and we'll probably bump to `5.0.0` in the not-too-long). I don't have `gulp` installed globally for `0.12` because it's not my system node. That makes this confusing. I don't think we should use `.node-version` in this context.

**Comment by erikjung** [comment]
@lyzadanger We should probably never include them. I'll remove it, and update the `.gitignore`.
