### ISSUE TITLE
Webpack ain't webpackin' nothin'

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/generator-core-patternlib#15]
Yo, our webpacks are MESSED. UP.

Y'know JavaScript? Yeah, you make a new project with this generator and you ain't compilin' _none_ of that.

Steps to reproduce:

1. Pull the latest generator, dawg.
2. Bro, generate a new project.
3. Witness the lack of ANY JS IN the `dist` directory, fool!!!

![tumblr_mldpkjdhh31s2gnjno1_400](https://cloud.githubusercontent.com/assets/69633/11938900/e865d7d2-a7d2-11e5-8a3b-2a92082e07f4.gif)

**Comment by erikjung** [comment]
Might be a change to the core JS Gulp task. Will look into it.

**Comment by erikjung** [comment]
@tylersticka I found the issue.

The generator uses `@latest` for all Node packages. Running it now will use Babel 6, which requires a little extra config to go into webpack. Fix coming shortly.

**Comment by erikjung** [comment]
Closed via #7
